name: Deploy Docker

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v3

      - name: Build Docker
        run: docker build -t meu-site .

      - name: Verificar imagem
        run: docker images